name:                cs584-project
version:             0.1.0.0
github:              "peschkaj/cs584-project"
license:             BSD3
author:              "Jeremiah Peschka"
maintainer:          "jeremiah.peschka@gmail.com"
copyright:           "2018 Jeremiah Peschka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/peschkaj/cs584-project#readme>

dependencies:
- base >= 4.7 && < 5
- stringsearch
- MissingH
- directory
- bytestring
- criterion

library:
  source-dirs: src

executables:
  cs584-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - "\"-with-rtsopts=-N -s -A10000m -IO -C -G1 -m100m -qa \""
    dependencies:
    - cs584-project

tests:
  cs584-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs584-project
